# Generated by Django 4.1.6 on 2023-02-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
