# Generated by Django 4.1.6 on 2023-02-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jiraAPI', '0002_delete_categories_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriesName', models.CharField(max_length=255)),
                ('categoriesDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodologyName', models.CharField(max_length=255)),
                ('methodologyDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('projectKey', models.CharField(max_length=100, null=True, unique=True)),
                ('dateCreateProject', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTypeName', models.CharField(max_length=255)),
                ('projectTypeDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraAPI.categories')),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraAPI.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='projectTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraAPI.projecttypes'),
        ),
    ]
