# Generated by Django 4.1.6 on 2023-02-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Methodology',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectTypeID',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projectName',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='ProjectTypes',
        ),
    ]
