# Generated by Django 4.1.6 on 2023-02-12 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jiraAPI', '0008_delete_methodology_remove_project_projecttypeid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriesName', models.CharField(max_length=150)),
                ('categoriesDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodologyName', models.CharField(max_length=150)),
                ('methodologyDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('projectKey', models.CharField(max_length=100, null=True, unique=True)),
                ('dateCreateProject', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTypeName', models.CharField(max_length=150)),
                ('projectTypeDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=200)),
                ('taskDescription', models.CharField(max_length=255)),
                ('dateCreateProject', models.DateTimeField(auto_now_add=True)),
                ('taskCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraAPI.categories')),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraAPI.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='projectTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraAPI.projecttypes'),
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboardTitle', models.CharField(max_length=150)),
                ('dashboardTaskName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraAPI.task')),
            ],
        ),
    ]
