# Generated by Django 4.1.6 on 2023-02-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='dashboardTaskName',
        ),
        migrations.DeleteModel(
            name='Methodology',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectTypeID',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projectName',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskCreator',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='ProjectTypes',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
