# Generated by Django 4.1.6 on 2023-02-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0013_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectTypes',
            new_name='ProjectType',
        ),
    ]
