# Generated by Django 4.1.6 on 2023-02-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0014_rename_projecttypes_projecttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Methodology',
        ),
        migrations.DeleteModel(
            name='RoadMap',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='dashboardTitle',
            new_name='dashBoardTitle',
        ),
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectTypeID',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
