# Generated by Django 4.1.6 on 2023-02-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0015_delete_methodology_delete_roadmap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='dashboardTaskName',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskCreator',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
