# Generated by Django 4.1.6 on 2023-02-16 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jiraAPI', '0016_remove_dashboard_dashboardtaskname_delete_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('projectKey', models.CharField(max_length=100, null=True, unique=True)),
                ('dateCreateProject', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('task_description', models.CharField(max_length=150, verbose_name='Описание задачи')),
                ('task_executor', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('task_files', models.FileField(upload_to='task_files/')),
                ('task_comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('task_date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('date_create_project', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания проекта')),
                ('task_grade', models.CharField(max_length=150)),
                ('task_remaning_time', models.IntegerField(verbose_name='Осталось времени на задачу')),
                ('task_spent_time', models.IntegerField(verbose_name='Потрачено времени на задачу')),
                ('sprint_status', models.CharField(max_length=150, verbose_name='Статус спринта')),
                ('task_apic', models.CharField(max_length=150)),
                ('task_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_title', models.CharField(max_length=150, verbose_name='Название Доски')),
                ('dashboard_task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraAPI.task')),
            ],
        ),
    ]
