# Generated by Django 4.1.6 on 2023-02-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0017_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_files',
        ),
    ]
