# Generated by Django 4.1.6 on 2023-02-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0018_remove_task_task_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_create_project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sprint_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_apic',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_comment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_creator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_date_create',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_executor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_grade',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_remaning_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_spent_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_title',
        ),
    ]
