# Generated by Django 4.1.6 on 2023-02-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0019_remove_task_date_create_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='dashboard_task_name',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
