# Generated by Django 4.1.6 on 2023-02-19 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jiraAPI', '0020_remove_dashboard_dashboard_task_name_delete_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('projectKey', models.CharField(max_length=100, null=True, unique=True)),
                ('dateCreateProject', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_Title', models.CharField(max_length=100, unique=True, verbose_name='Название задачи')),
                ('task_Description', models.CharField(max_length=150, verbose_name='Описание задачи')),
                ('task_Executor', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('task_Files', models.FileField(upload_to='task_files/')),
                ('task_Comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('task_Date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('task_Date_change', models.DateTimeField(auto_now_add=True)),
                ('task_Grade', models.CharField(max_length=150)),
                ('task_Remaning_time', models.IntegerField(verbose_name='Осталось времени на задачу')),
                ('task_Spent_time', models.IntegerField(verbose_name='Потрачено времени на задачу')),
                ('sprint_Status', models.CharField(max_length=150, verbose_name='Статус спринта')),
                ('task_Apic', models.CharField(max_length=150)),
                ('task_Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_title', models.CharField(max_length=150, verbose_name='Название Доски')),
                ('dashboard_task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiraAPI.task')),
            ],
        ),
    ]
