# Generated by Django 4.1.6 on 2023-02-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0021_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_Title',
            new_name='task_title',
        ),
    ]
