# Generated by Django 4.1.6 on 2023-02-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0023_rename_task_description_task_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_Creator',
            new_name='task_creator',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_Executor',
            new_name='task_executor',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_Files',
            new_name='task_files',
        ),
    ]
