# Generated by Django 4.1.6 on 2023-02-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0024_rename_task_creator_task_task_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_Comment',
            new_name='task_comment',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_Date_change',
            new_name='task_date_change',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_Date_create',
            new_name='task_date_create',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_Grade',
            new_name='task_grade',
        ),
    ]
