# Generated by Django 4.1.6 on 2023-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0027_alter_task_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_remaning_time',
            field=models.IntegerField(blank=True, verbose_name='Осталось времени на задачу'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Название задачи'),
        ),
    ]
