# Generated by Django 4.1.6 on 2023-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0028_alter_task_task_comment_alter_task_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_files',
            field=models.FileField(null=True, upload_to='task_files/'),
        ),
    ]
