# Generated by Django 4.1.6 on 2023-02-19 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jiraAPI', '0029_alter_task_task_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_creator',
            field=models.CharField(max_length=100, verbose_name='Создал задачу'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
