# Generated by Django 4.1.6 on 2023-02-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiraAPI', '0030_alter_task_task_creator_alter_task_task_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_date_change',
        ),
        migrations.AddField(
            model_name='task',
            name='task_date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
